name: contacts
description: "A mobile app that helps users manage their contacts by adding, editing, and viewing information easily. It focuses on simple navigation and a clear, organized design."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  lottie: ^3.3.2
  flutter_native_splash: ^2.4.7
  image_picker: ^1.2.1
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter_Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "#29384D"
  image_path: "assets/images/ic_luncher.png"